short_open_tag bug
Hello
Please modify this since it will throw an exception if php_value short_open_tag = Off (as it should according to the app/check.php):

RuntimeException: The autoloader expected class "Shtumi\UsefulBundle\Form\DataTransformer\DateRangeToValueTransformer" to be defined in file "<project>/app/../vendor/bundles/Shtumi/UsefulBundle/Form/DataTransformer/DateRangeToValueTransformer.php". The file was found but the class was not in it, the class name or namespace probably has a typo. (uncaught exception) at <project>/vendor/symfony/src/Symfony/Component/ClassLoader/DebugUniversalClassLoader.php line 58 

Hope that helps!
lemme know if i need to provide any other info or what not !!
thx
Vinz